### ISSUE TITLE
Generating bingos pdf bug

### ISSUE THREAD

**Issue by saczmateusz** [kryha5555/Bingo-Generator#1]
6 bingos can't fit one page using default settings.
[img](https://imgur.com/bS78b83)

Tested on:
Google Chrome | 79.0.3945.79 (Official Build) (64-bit)
OS | Linux Mint 19.2 Cinnamon
JavaScript | V8 7.9.317.31

:PepeLaugh:

**Comment by kryha5555** [comment]
it works on my machine
